// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: threat_vector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoError int32

const (
	GeoError_GEO_ERROR_NONE         GeoError = 0
	GeoError_GEO_ERROR_PRIVATE_IP   GeoError = 1
	GeoError_GEO_ERROR_LOOKUP_MISS  GeoError = 2
	GeoError_GEO_ERROR_RATE_LIMITED GeoError = 3
	GeoError_GEO_ERROR_TIMEOUT      GeoError = 4
	GeoError_GEO_ERROR_INVALID_IP   GeoError = 5
	GeoError_GEO_ERROR_INTERNAL     GeoError = 6
)

// Enum value maps for GeoError.
var (
	GeoError_name = map[int32]string{
		0: "GEO_ERROR_NONE",
		1: "GEO_ERROR_PRIVATE_IP",
		2: "GEO_ERROR_LOOKUP_MISS",
		3: "GEO_ERROR_RATE_LIMITED",
		4: "GEO_ERROR_TIMEOUT",
		5: "GEO_ERROR_INVALID_IP",
		6: "GEO_ERROR_INTERNAL",
	}
	GeoError_value = map[string]int32{
		"GEO_ERROR_NONE":         0,
		"GEO_ERROR_PRIVATE_IP":   1,
		"GEO_ERROR_LOOKUP_MISS":  2,
		"GEO_ERROR_RATE_LIMITED": 3,
		"GEO_ERROR_TIMEOUT":      4,
		"GEO_ERROR_INVALID_IP":   5,
		"GEO_ERROR_INTERNAL":     6,
	}
)

func (x GeoError) Enum() *GeoError {
	p := new(GeoError)
	*p = x
	return p
}

func (x GeoError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoError) Descriptor() protoreflect.EnumDescriptor {
	return file_threat_vector_proto_enumTypes[0].Descriptor()
}

func (GeoError) Type() protoreflect.EnumType {
	return &file_threat_vector_proto_enumTypes[0]
}

func (x GeoError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoError.Descriptor instead.
func (GeoError) EnumDescriptor() ([]byte, []int) {
	return file_threat_vector_proto_rawDescGZIP(), []int{0}
}

type AttackEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uniq id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// attacker info
	AttackerGeo *GeoPoint `protobuf:"bytes,2,opt,name=attacker_geo,json=attackerGeo,proto3" json:"attacker_geo,omitempty"`
	// target info
	TargetGeo *GeoPoint `protobuf:"bytes,3,opt,name=target_geo,json=targetGeo,proto3" json:"target_geo,omitempty"`
	// severity level (0 - 100) - visual intensity, color and etc
	Severity int32 `protobuf:"varint,4,opt,name=severity,proto3" json:"severity,omitempty"`
	// unix timestamps milisec
	StartTs       int64 `protobuf:"varint,5,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs         int64 `protobuf:"varint,6,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEvent) Reset() {
	*x = AttackEvent{}
	mi := &file_threat_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEvent) ProtoMessage() {}

func (x *AttackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_threat_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEvent.ProtoReflect.Descriptor instead.
func (*AttackEvent) Descriptor() ([]byte, []int) {
	return file_threat_vector_proto_rawDescGZIP(), []int{0}
}

func (x *AttackEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttackEvent) GetAttackerGeo() *GeoPoint {
	if x != nil {
		return x.AttackerGeo
	}
	return nil
}

func (x *AttackEvent) GetTargetGeo() *GeoPoint {
	if x != nil {
		return x.TargetGeo
	}
	return nil
}

func (x *AttackEvent) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *AttackEvent) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *AttackEvent) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

type GeoPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// coordinates
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// why geo resolution failed (if coordinates are 0,0)
	Error         GeoError `protobuf:"varint,3,opt,name=error,proto3,enum=threatvector.GeoError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_threat_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_threat_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_threat_vector_proto_rawDescGZIP(), []int{1}
}

func (x *GeoPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoPoint) GetError() GeoError {
	if x != nil {
		return x.Error
	}
	return GeoError_GEO_ERROR_NONE
}

var File_threat_vector_proto protoreflect.FileDescriptor

const file_threat_vector_proto_rawDesc = "" +
	"\n" +
	"\x13threat_vector.proto\x12\fthreatvector\"\xdd\x01\n" +
	"\vAttackEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\fattacker_geo\x18\x02 \x01(\v2\x16.threatvector.GeoPointR\vattackerGeo\x125\n" +
	"\n" +
	"target_geo\x18\x03 \x01(\v2\x16.threatvector.GeoPointR\ttargetGeo\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x05R\bseverity\x12\x19\n" +
	"\bstart_ts\x18\x05 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x06 \x01(\x03R\x05endTs\"r\n" +
	"\bGeoPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12,\n" +
	"\x05error\x18\x03 \x01(\x0e2\x16.threatvector.GeoErrorR\x05error*\xb8\x01\n" +
	"\bGeoError\x12\x12\n" +
	"\x0eGEO_ERROR_NONE\x10\x00\x12\x18\n" +
	"\x14GEO_ERROR_PRIVATE_IP\x10\x01\x12\x19\n" +
	"\x15GEO_ERROR_LOOKUP_MISS\x10\x02\x12\x1a\n" +
	"\x16GEO_ERROR_RATE_LIMITED\x10\x03\x12\x15\n" +
	"\x11GEO_ERROR_TIMEOUT\x10\x04\x12\x18\n" +
	"\x14GEO_ERROR_INVALID_IP\x10\x05\x12\x16\n" +
	"\x12GEO_ERROR_INTERNAL\x10\x06B#Z!icarus-vision/backend/internal/pbb\x06proto3"

var (
	file_threat_vector_proto_rawDescOnce sync.Once
	file_threat_vector_proto_rawDescData []byte
)

func file_threat_vector_proto_rawDescGZIP() []byte {
	file_threat_vector_proto_rawDescOnce.Do(func() {
		file_threat_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threat_vector_proto_rawDesc), len(file_threat_vector_proto_rawDesc)))
	})
	return file_threat_vector_proto_rawDescData
}

var file_threat_vector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_threat_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_threat_vector_proto_goTypes = []any{
	(GeoError)(0),       // 0: threatvector.GeoError
	(*AttackEvent)(nil), // 1: threatvector.AttackEvent
	(*GeoPoint)(nil),    // 2: threatvector.GeoPoint
}
var file_threat_vector_proto_depIdxs = []int32{
	2, // 0: threatvector.AttackEvent.attacker_geo:type_name -> threatvector.GeoPoint
	2, // 1: threatvector.AttackEvent.target_geo:type_name -> threatvector.GeoPoint
	0, // 2: threatvector.GeoPoint.error:type_name -> threatvector.GeoError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_threat_vector_proto_init() }
func file_threat_vector_proto_init() {
	if File_threat_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threat_vector_proto_rawDesc), len(file_threat_vector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_threat_vector_proto_goTypes,
		DependencyIndexes: file_threat_vector_proto_depIdxs,
		EnumInfos:         file_threat_vector_proto_enumTypes,
		MessageInfos:      file_threat_vector_proto_msgTypes,
	}.Build()
	File_threat_vector_proto = out.File
	file_threat_vector_proto_goTypes = nil
	file_threat_vector_proto_depIdxs = nil
}
